//! Launching `audiocpp_server` in terminals (design §4). Every mode starts from the same
//! generated launcher script, which records its PID and then `exec`s the server, so the PID
//! in the pidfile *is* the server.

use std::ffi::OsStr;
use std::net::{SocketAddr, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Duration;

use crate::config::{Config, Launch, ServerConfig, TerminalMode};
use crate::error::{Error, IoContext, Result};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TargetOs {
    Linux,
    MacOs,
    Windows,
}

impl TargetOs {
    pub fn current() -> TargetOs {
        if cfg!(windows) {
            TargetOs::Windows
        } else if cfg!(target_os = "macos") {
            TargetOs::MacOs
        } else {
            TargetOs::Linux
        }
    }
}

/// Everything needed to write a launcher for one server.
#[derive(Clone, Debug, PartialEq)]
pub struct LaunchPlan {
    pub name: String,
    pub port: u16,
    /// Binary followed by its arguments.
    pub argv: Vec<String>,
    pub working_dir: Option<PathBuf>,
    pub run_dir: PathBuf,
}

/// Server arguments: the configured extras, then backend, device and port (§4).
pub fn server_args(launch: &Launch, port: u16) -> Vec<String> {
    let mut a = launch.extra_args.clone();
    a.push("--backend".into());
    a.push(launch.backend.clone());
    if let Some(d) = launch.device {
        a.push("--device".into());
        a.push(d.to_string());
    }
    a.push("--port".into());
    a.push(port.to_string());
    a
}

impl LaunchPlan {
    pub fn new(cfg: &Config, server: &ServerConfig, run_dir: &Path) -> Result<LaunchPlan> {
        let launch = server.launch.as_ref().ok_or_else(|| {
            Error::Launcher(format!("`{}` is attach-only (no `launch`)", server.name))
        })?;
        let bin = cfg
            .server_binary
            .as_ref()
            .ok_or_else(|| Error::Launcher("`server_binary` is not set".into()))?;
        let mut argv = vec![bin.to_string_lossy().into_owned()];
        argv.extend(server_args(launch, server.port));
        Ok(LaunchPlan {
            name: server.name.clone(),
            port: server.port,
            argv,
            working_dir: cfg.working_dir.clone(),
            run_dir: run_dir.to_path_buf(),
        })
    }

    pub fn title(&self) -> String {
        format!("audiocpp {} :{}", self.name, self.port)
    }

    pub fn pidfile(&self) -> PathBuf {
        self.run_dir.join(format!("{}.pid", self.name))
    }

    pub fn script_path(&self, os: TargetOs) -> PathBuf {
        let ext = match os {
            TargetOs::Linux => "sh",
            TargetOs::MacOs => "command",
            TargetOs::Windows => "cmd",
        };
        self.run_dir.join(format!("{}.{ext}", self.name))
    }

    pub fn desktop_path(&self) -> PathBuf {
        self.run_dir.join(format!("{}.desktop", self.name))
    }

    /// POSIX launcher (`.sh` on Linux, `.command` on macOS).
    pub fn unix_script(&self) -> String {
        let mut s = String::from("#!/bin/sh\n");
        s += &format!("# generated by audiocpp-ui — {}\n", self.name);
        s += &format!("printf '\\033]0;%s\\007' {}\n", sh_quote(&self.title()));
        s += &format!(
            "echo $$ > {}\n",
            sh_quote(&self.pidfile().to_string_lossy())
        );
        if let Some(d) = &self.working_dir {
            s += &format!("cd {} || exit 1\n", sh_quote(&d.to_string_lossy()));
        }
        let cmd: Vec<String> = self.argv.iter().map(|a| sh_quote(a)).collect();
        s += &format!("exec {}\n", cmd.join(" "));
        s
    }

    /// Linux `.desktop` entry with `Terminal=true`; `Exec` points to the script (§4.1.1).
    pub fn desktop_entry(&self) -> String {
        let mut s = String::from("[Desktop Entry]\nType=Application\n");
        s += &format!("Name=audiocpp {} (:{})\n", self.name, self.port);
        s += &format!(
            "Exec={}\n",
            desktop_escape(&self.script_path(TargetOs::Linux).to_string_lossy())
        );
        if let Some(d) = &self.working_dir {
            s += &format!("Path={}\n", d.to_string_lossy());
        }
        s += "Terminal=true\nNoDisplay=true\n";
        s
    }

    /// Windows `.cmd`: no `exec`, so PowerShell starts the server and records *its* PID.
    pub fn windows_cmd(&self) -> String {
        let mut s = String::from("@echo off\r\n");
        s += &format!("rem generated by audiocpp-ui - {}\r\n", self.name);
        s += &format!("title {}\r\n", self.title());
        if let Some(d) = &self.working_dir {
            s += &format!("cd /d \"{}\"\r\n", d.to_string_lossy());
        }
        let args: Vec<String> = self.argv[1..].iter().map(|a| ps_quote(a)).collect();
        let arglist = if args.is_empty() {
            String::new()
        } else {
            format!(" -ArgumentList @({})", args.join(","))
        };
        s += &format!(
            "powershell -NoProfile -Command \"$p = Start-Process -NoNewWindow -PassThru -FilePath {}{arglist}; $p.Id | Out-File -Encoding ascii {}; $p.WaitForExit()\"\r\n",
            ps_quote(&self.argv[0]),
            ps_quote(&self.pidfile().to_string_lossy()),
        );
        s
    }

    /// Writes the launcher files for `os` and returns the file to open.
    pub fn write_files(&self, os: TargetOs) -> Result<PathBuf> {
        std::fs::create_dir_all(&self.run_dir).at(&self.run_dir)?;
        let _ = std::fs::remove_file(self.pidfile());
        let script = self.script_path(os);
        let body = match os {
            TargetOs::Windows => self.windows_cmd(),
            _ => self.unix_script(),
        };
        std::fs::write(&script, body).at(&script)?;
        make_executable(&script)?;
        if os == TargetOs::Linux {
            let d = self.desktop_path();
            std::fs::write(&d, self.desktop_entry()).at(&d)?;
            make_executable(&d)?;
            return Ok(d);
        }
        Ok(script)
    }
}

#[cfg(unix)]
fn make_executable(p: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(p, std::fs::Permissions::from_mode(0o755)).at(p)
}

#[cfg(not(unix))]
fn make_executable(_: &Path) -> Result<()> {
    Ok(())
}

pub fn sh_quote(s: &str) -> String {
    if !s.is_empty()
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || "-_./:=@%+,".contains(c))
    {
        return s.to_string();
    }
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn ps_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn desktop_escape(s: &str) -> String {
    if s.chars()
        .any(|c| c.is_whitespace() || "\"'\\$`".contains(c))
    {
        format!(
            "\"{}\"",
            s.replace('\\', "\\\\")
                .replace('"', "\\\"")
                .replace('$', "\\$")
                .replace('`', "\\`")
        )
    } else {
        s.to_string()
    }
}

// ---------------------------------------------------------------------------------------
// Openers (§4.1.1)

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Opener {
    Gio(PathBuf),
    Kioclient(PathBuf),
    Dex(PathBuf),
    XdgOpen(PathBuf),
    MacOpen { app: String },
    WindowsTerminal,
    WindowsStart,
}

impl Opener {
    pub fn describe(&self) -> String {
        match self {
            Opener::Gio(_) => "gio launch".into(),
            Opener::Kioclient(p) => format!(
                "{} exec",
                p.file_name().unwrap_or_default().to_string_lossy()
            ),
            Opener::Dex(_) => "dex".into(),
            Opener::XdgOpen(_) => "xdg-open (may open an editor instead)".into(),
            Opener::MacOpen { app } => format!("open -a {app}"),
            Opener::WindowsTerminal => "Windows Terminal (wt)".into(),
            Opener::WindowsStart => "cmd /c start".into(),
        }
    }

    /// Command line that opens `file` (the `.desktop`, `.command` or `.cmd`).
    pub fn argv(&self, file: &Path, title: &str) -> Vec<String> {
        let f = file.to_string_lossy().into_owned();
        match self {
            Opener::Gio(p) => vec![p.to_string_lossy().into_owned(), "launch".into(), f],
            Opener::Kioclient(p) => vec![p.to_string_lossy().into_owned(), "exec".into(), f],
            Opener::Dex(p) | Opener::XdgOpen(p) => vec![p.to_string_lossy().into_owned(), f],
            Opener::MacOpen { app } => vec!["open".into(), "-a".into(), app.clone(), f],
            Opener::WindowsTerminal => vec![
                "wt".into(),
                "new-tab".into(),
                "--title".into(),
                title.into(),
                f,
            ],
            Opener::WindowsStart => {
                vec![
                    "cmd".into(),
                    "/c".into(),
                    "start".into(),
                    format!("\"{title}\""),
                    "cmd".into(),
                    "/k".into(),
                    f,
                ]
            }
        }
    }
}

/// Linux opener order: `gio launch` → `kioclient exec` → `dex` → `xdg-open` (last resort,
/// often opens a text editor). `path` is the `PATH` to search.
pub fn probe_linux_opener(path: &OsStr) -> Option<Opener> {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("/"));
    let find = |b: &str| which::which_in(b, Some(path), &cwd).ok();
    if let Some(p) = find("gio") {
        return Some(Opener::Gio(p));
    }
    for k in ["kioclient6", "kioclient5", "kioclient"] {
        if let Some(p) = find(k) {
            return Some(Opener::Kioclient(p));
        }
    }
    if let Some(p) = find("dex") {
        return Some(Opener::Dex(p));
    }
    find("xdg-open").map(Opener::XdgOpen)
}

/// The native opener for this OS, or `None` if nothing usable exists.
pub fn detect_opener(cfg: &Config) -> Option<Opener> {
    match TargetOs::current() {
        TargetOs::Linux => probe_linux_opener(&std::env::var_os("PATH").unwrap_or_default()),
        TargetOs::MacOs => Some(Opener::MacOpen {
            app: cfg
                .macos_terminal_app
                .clone()
                .unwrap_or_else(|| "Terminal".into()),
        }),
        TargetOs::Windows => {
            if which::which("wt").is_ok() {
                Some(Opener::WindowsTerminal)
            } else {
                Some(Opener::WindowsStart)
            }
        }
    }
}

/// Per-user runtime directory for scripts and pidfiles (§4.1).
pub fn runtime_dir() -> PathBuf {
    let base = directories::BaseDirs::new();
    let fallback = std::env::temp_dir().join(crate::config::APP_NAME);
    let Some(b) = base else { return fallback };
    match TargetOs::current() {
        TargetOs::Linux => match b.runtime_dir() {
            Some(r) => r.join(crate::config::APP_NAME),
            None => b.cache_dir().join(crate::config::APP_NAME).join("run"),
        },
        TargetOs::MacOs => b.cache_dir().join(crate::config::APP_NAME).join("run"),
        TargetOs::Windows => b.data_local_dir().join(crate::config::APP_NAME).join("run"),
    }
}

// ---------------------------------------------------------------------------------------
// Launching

pub enum Launched {
    /// Running in a terminal the app doesn't own; track it by pidfile.
    Detached,
    /// `Headless`: the app owns the process and its output.
    Headless(tokio::process::Child),
}

/// Expands `{script}` and `{name}` in a `terminal: Command([...])` template.
pub fn expand_command(template: &[String], script: &Path, name: &str) -> Vec<String> {
    template
        .iter()
        .map(|a| {
            a.replace("{script}", &script.to_string_lossy())
                .replace("{name}", name)
        })
        .collect()
}

pub fn launch(plan: &LaunchPlan, mode: &TerminalMode, opener: Option<&Opener>) -> Result<Launched> {
    let os = TargetOs::current();
    match mode {
        TerminalMode::Headless => {
            let script = plan.write_files(os)?;
            let mut cmd = if os == TargetOs::Windows {
                // no terminal and no exec: run the server directly and record its PID
                let mut c = tokio::process::Command::new(&plan.argv[0]);
                c.args(&plan.argv[1..]);
                if let Some(d) = &plan.working_dir {
                    c.current_dir(d);
                }
                c
            } else {
                let mut c = tokio::process::Command::new("/bin/sh");
                c.arg(plan.script_path(os));
                c
            };
            let _ = script;
            cmd.stdin(Stdio::null())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped());
            let child = cmd
                .spawn()
                .map_err(|e| Error::Launcher(format!("spawning {}: {e}", plan.argv[0])))?;
            if os == TargetOs::Windows
                && let Some(pid) = child.id()
            {
                std::fs::write(plan.pidfile(), pid.to_string()).at(plan.pidfile())?;
            }
            Ok(Launched::Headless(child))
        }
        TerminalMode::Command(template) => {
            plan.write_files(os)?;
            let script = plan.script_path(os);
            let argv = expand_command(template, &script, &plan.name);
            spawn_detached(&argv)?;
            Ok(Launched::Detached)
        }
        TerminalMode::Native => {
            let file = plan.write_files(os)?;
            let opener = opener.ok_or_else(|| {
                Error::Launcher(
                    "no terminal opener found (gio, kioclient, dex, xdg-open); set `terminal: Command([...])` in the config".into(),
                )
            })?;
            spawn_detached(&opener.argv(&file, &plan.title()))?;
            Ok(Launched::Detached)
        }
    }
}

fn spawn_detached(argv: &[String]) -> Result<()> {
    let (bin, args) = argv
        .split_first()
        .ok_or_else(|| Error::Launcher("empty command".into()))?;
    let mut child = Command::new(bin)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| Error::Launcher(format!("`{bin}`: {e}")))?;
    // reap the opener in the background (it usually exits right away)
    std::thread::spawn(move || {
        let _ = child.wait();
    });
    Ok(())
}

// ---------------------------------------------------------------------------------------
// Process and port tracking (§4.2)

pub fn read_pid(pidfile: &Path) -> Option<u32> {
    std::fs::read_to_string(pidfile)
        .ok()?
        .trim()
        .trim_start_matches('\u{feff}')
        .parse()
        .ok()
}

#[cfg(unix)]
pub fn pid_alive(pid: u32) -> bool {
    use nix::sys::signal::kill;
    use nix::unistd::Pid;
    if pid == 0 {
        return false;
    }
    // a zombie still answers kill(0); treat it as gone
    if let Ok(stat) = std::fs::read_to_string(format!("/proc/{pid}/stat"))
        && let Some(rest) = stat.rsplit_once(')').map(|(_, r)| r.trim_start())
        && (rest.starts_with('Z') || rest.starts_with('X'))
    {
        return false;
    }
    match kill(Pid::from_raw(pid as i32), None) {
        Ok(()) => true,
        Err(nix::errno::Errno::EPERM) => true,
        Err(_) => false,
    }
}

#[cfg(windows)]
pub fn pid_alive(pid: u32) -> bool {
    Command::new("tasklist")
        .args(["/FI", &format!("PID eq {pid}"), "/NH"])
        .output()
        .map(|o| {
            String::from_utf8_lossy(&o.stdout)
                .split_whitespace()
                .any(|w| w == pid.to_string())
        })
        .unwrap_or(false)
}

/// SIGTERM (Unix) or `taskkill /T` (Windows).
pub fn terminate(pid: u32, force: bool) -> Result<()> {
    #[cfg(unix)]
    {
        use nix::sys::signal::{Signal, kill};
        use nix::unistd::Pid;
        let sig = if force {
            Signal::SIGKILL
        } else {
            Signal::SIGTERM
        };
        match kill(Pid::from_raw(pid as i32), sig) {
            Ok(()) | Err(nix::errno::Errno::ESRCH) => Ok(()),
            Err(e) => Err(Error::Launcher(format!("kill {pid}: {e}"))),
        }
    }
    #[cfg(windows)]
    {
        let mut c = Command::new("taskkill");
        c.args(["/PID", &pid.to_string(), "/T"]);
        if force {
            c.arg("/F");
        }
        c.output()
            .map_err(|e| Error::Launcher(format!("taskkill: {e}")))?;
        Ok(())
    }
}

/// True if something accepts TCP connections on `127.0.0.1:port`.
pub fn port_open(port: u16) -> bool {
    let addr = SocketAddr::from(([127, 0, 0, 1], port));
    TcpStream::connect_timeout(&addr, Duration::from_millis(300)).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    fn plan() -> LaunchPlan {
        LaunchPlan {
            name: "gpu1".into(),
            port: 9123,
            argv: std::iter::once("./audiocpp_server".to_string())
                .chain(server_args(
                    &Launch {
                        backend: "vulkan".into(),
                        device: Some(1),
                        extra_args: vec!["--ui".into(), "--ui-management".into(), "--log".into()],
                        autostart: true,
                    },
                    9123,
                ))
                .collect(),
            working_dir: Some("/opt/audiocpp".into()),
            run_dir: "/run/user/1000/audiocpp-ui".into(),
        }
    }

    #[test]
    fn golden_sh() {
        assert_eq!(
            plan().unix_script(),
            r#"#!/bin/sh
# generated by audiocpp-ui — gpu1
printf '\033]0;%s\007' 'audiocpp gpu1 :9123'
echo $$ > /run/user/1000/audiocpp-ui/gpu1.pid
cd /opt/audiocpp || exit 1
exec ./audiocpp_server --ui --ui-management --log --backend vulkan --device 1 --port 9123
"#
        );
    }

    #[test]
    fn golden_desktop() {
        assert_eq!(
            plan().desktop_entry(),
            "[Desktop Entry]\nType=Application\nName=audiocpp gpu1 (:9123)\nExec=/run/user/1000/audiocpp-ui/gpu1.sh\nPath=/opt/audiocpp\nTerminal=true\nNoDisplay=true\n"
        );
    }

    #[test]
    fn golden_command_is_the_unix_script() {
        let p = plan();
        assert_eq!(
            p.script_path(TargetOs::MacOs),
            PathBuf::from("/run/user/1000/audiocpp-ui/gpu1.command")
        );
        assert!(p.unix_script().starts_with("#!/bin/sh\n"));
    }

    #[test]
    fn golden_cmd() {
        let mut p = plan();
        p.argv[0] = r"C:\audiocpp\audiocpp_server.exe".into();
        p.working_dir = Some(r"C:\audiocpp".into());
        p.run_dir = r"C:\Users\me\AppData\Local\audiocpp-ui\run".into();
        let pid = p.pidfile().to_string_lossy().into_owned();
        assert_eq!(
            p.windows_cmd(),
            format!(
                "@echo off\r\nrem generated by audiocpp-ui - gpu1\r\ntitle audiocpp gpu1 :9123\r\ncd /d \"C:\\audiocpp\"\r\npowershell -NoProfile -Command \"$p = Start-Process -NoNewWindow -PassThru -FilePath 'C:\\audiocpp\\audiocpp_server.exe' -ArgumentList @('--ui','--ui-management','--log','--backend','vulkan','--device','1','--port','9123'); $p.Id | Out-File -Encoding ascii '{pid}'; $p.WaitForExit()\"\r\n"
            )
        );
    }

    #[test]
    fn quoting() {
        assert_eq!(sh_quote("plain-1.0"), "plain-1.0");
        assert_eq!(sh_quote("a b"), "'a b'");
        assert_eq!(sh_quote("it's"), "'it'\\''s'");
        assert_eq!(sh_quote(""), "''");
        assert_eq!(desktop_escape("/a b/x.sh"), "\"/a b/x.sh\"");
    }

    #[test]
    fn command_template_expands() {
        let t: Vec<String> = ["kitty", "--title", "{name}", "--", "{script}"]
            .map(String::from)
            .to_vec();
        assert_eq!(
            expand_command(&t, Path::new("/r/gpu1.sh"), "gpu1"),
            vec!["kitty", "--title", "gpu1", "--", "/r/gpu1.sh"]
        );
    }

    #[cfg(unix)]
    #[test]
    fn opener_probe_order() {
        use std::os::unix::fs::PermissionsExt;
        let d = tempfile::tempdir().unwrap();
        let mk = |n: &str| {
            let p = d.path().join(n);
            std::fs::write(&p, "#!/bin/sh\n").unwrap();
            std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o755)).unwrap();
            p
        };
        let path = d.path().as_os_str().to_owned();
        assert_eq!(probe_linux_opener(&path), None);
        let x = mk("xdg-open");
        assert_eq!(probe_linux_opener(&path), Some(Opener::XdgOpen(x)));
        let dex = mk("dex");
        assert_eq!(probe_linux_opener(&path), Some(Opener::Dex(dex)));
        let k = mk("kioclient5");
        assert_eq!(
            probe_linux_opener(&path),
            Some(Opener::Kioclient(k.clone()))
        );
        let g = mk("gio");
        let o = probe_linux_opener(&path).unwrap();
        assert_eq!(o, Opener::Gio(g.clone()));
        assert_eq!(
            o.argv(Path::new("/r/gpu1.desktop"), "t"),
            vec![
                g.to_string_lossy().into_owned(),
                "launch".into(),
                "/r/gpu1.desktop".into()
            ]
        );
        assert_eq!(Opener::Kioclient(k).argv(Path::new("/f"), "t")[1], "exec");
    }

    #[test]
    fn windows_openers() {
        assert_eq!(
            Opener::WindowsTerminal.argv(Path::new("x.cmd"), "gpu1"),
            vec!["wt", "new-tab", "--title", "gpu1", "x.cmd"]
        );
        assert_eq!(
            Opener::WindowsStart.argv(Path::new("x.cmd"), "gpu1"),
            vec!["cmd", "/c", "start", "\"gpu1\"", "cmd", "/k", "x.cmd"]
        );
        assert_eq!(
            Opener::MacOpen {
                app: "iTerm".into()
            }
            .argv(Path::new("x.command"), "t"),
            vec!["open", "-a", "iTerm", "x.command"]
        );
    }

    #[test]
    fn writes_files() {
        let d = tempfile::tempdir().unwrap();
        let mut p = plan();
        p.run_dir = d.path().to_path_buf();
        let f = p.write_files(TargetOs::Linux).unwrap();
        assert_eq!(f, d.path().join("gpu1.desktop"));
        assert!(d.path().join("gpu1.sh").is_file());
        let f = p.write_files(TargetOs::Windows).unwrap();
        assert_eq!(f, d.path().join("gpu1.cmd"));
    }

    #[cfg(unix)]
    #[test]
    fn pid_tracking() {
        assert!(pid_alive(std::process::id()));
        assert!(!pid_alive(0));
        let mut c = Command::new("sleep").arg("0").spawn().unwrap();
        let pid = c.id();
        c.wait().unwrap();
        assert!(!pid_alive(pid));
    }
}
